[2025-04-20 09:52:31] ERROR: Error al cargar datos: list index out of range
Traceback (most recent call last):
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adaptive_multifactor_strategy.py", line 266, in _load_data
    data = all_data[0]
           ~~~~~~~~^^^
IndexError: list index out of range
[2025-04-20 09:52:31] ERROR: Error al inicializar estrategia: list index out of range
Traceback (most recent call last):
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adapter_alpaca.py", line 213, in initialize_strategy
    self.strategy = AdaptiveMultifactorStrategy(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adaptive_multifactor_strategy.py", line 183, in __init__
    self._load_data()
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adaptive_multifactor_strategy.py", line 266, in _load_data
    data = all_data[0]
           ~~~~~~~~^^^
IndexError: list index out of range
[2025-04-20 09:52:36] ERROR: Error al cargar datos: list index out of range
Traceback (most recent call last):
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adaptive_multifactor_strategy.py", line 266, in _load_data
    data = all_data[0]
           ~~~~~~~~^^^
IndexError: list index out of range
[2025-04-20 09:52:36] ERROR: Error al inicializar estrategia: list index out of range
Traceback (most recent call last):
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adapter_alpaca.py", line 213, in initialize_strategy
    self.strategy = AdaptiveMultifactorStrategy(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adaptive_multifactor_strategy.py", line 183, in __init__
    self._load_data()
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adaptive_multifactor_strategy.py", line 266, in _load_data
    data = all_data[0]
           ~~~~~~~~^^^
IndexError: list index out of range
[2025-04-20 09:52:36] ERROR: No se pudo inicializar la estrategia
[2025-04-20 09:55:09] ERROR: Error al cargar datos: list index out of range
Traceback (most recent call last):
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adaptive_multifactor_strategy.py", line 266, in _load_data
    data = all_data[0]
           ~~~~~~~~^^^
IndexError: list index out of range
[2025-04-20 09:55:09] ERROR: Error al inicializar estrategia: list index out of range
Traceback (most recent call last):
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adapter_alpaca.py", line 213, in initialize_strategy
    self.strategy = AdaptiveMultifactorStrategy(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adaptive_multifactor_strategy.py", line 183, in __init__
    self._load_data()
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adaptive_multifactor_strategy.py", line 266, in _load_data
    data = all_data[0]
           ~~~~~~~~^^^
IndexError: list index out of range
[2025-04-20 09:55:14] ERROR: Error al cargar datos: list index out of range
Traceback (most recent call last):
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adaptive_multifactor_strategy.py", line 266, in _load_data
    data = all_data[0]
           ~~~~~~~~^^^
IndexError: list index out of range
[2025-04-20 09:55:14] ERROR: Error al inicializar estrategia: list index out of range
Traceback (most recent call last):
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adapter_alpaca.py", line 213, in initialize_strategy
    self.strategy = AdaptiveMultifactorStrategy(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adaptive_multifactor_strategy.py", line 183, in __init__
    self._load_data()
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adaptive_multifactor_strategy.py", line 266, in _load_data
    data = all_data[0]
           ~~~~~~~~^^^
IndexError: list index out of range
[2025-04-20 09:55:14] ERROR: No se pudo inicializar la estrategia
[2025-04-20 09:58:54] ERROR: Error al cargar datos: list index out of range
Traceback (most recent call last):
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adaptive_multifactor_strategy.py", line 266, in _load_data
    data = all_data[0]
           ~~~~~~~~^^^
IndexError: list index out of range
[2025-04-20 09:58:54] ERROR: Error al inicializar estrategia: list index out of range
Traceback (most recent call last):
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adapter_alpaca.py", line 214, in initialize_strategy
    self.strategy = AdaptiveMultifactorStrategy(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adaptive_multifactor_strategy.py", line 183, in __init__
    self._load_data()
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adaptive_multifactor_strategy.py", line 266, in _load_data
    data = all_data[0]
           ~~~~~~~~^^^
IndexError: list index out of range
[2025-04-20 09:58:59] ERROR: Error al cargar datos: list index out of range
Traceback (most recent call last):
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adaptive_multifactor_strategy.py", line 266, in _load_data
    data = all_data[0]
           ~~~~~~~~^^^
IndexError: list index out of range
[2025-04-20 09:58:59] ERROR: Error al inicializar estrategia: list index out of range
Traceback (most recent call last):
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adapter_alpaca.py", line 214, in initialize_strategy
    self.strategy = AdaptiveMultifactorStrategy(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adaptive_multifactor_strategy.py", line 183, in __init__
    self._load_data()
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adaptive_multifactor_strategy.py", line 266, in _load_data
    data = all_data[0]
           ~~~~~~~~^^^
IndexError: list index out of range
[2025-04-20 09:58:59] ERROR: No se pudo inicializar la estrategia
[2025-04-20 09:59:30] ERROR: Error al cargar datos: list index out of range
Traceback (most recent call last):
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adaptive_multifactor_strategy.py", line 266, in _load_data
    data = all_data[0]
           ~~~~~~~~^^^
IndexError: list index out of range
[2025-04-20 09:59:30] ERROR: Error al inicializar estrategia: list index out of range
Traceback (most recent call last):
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adapter_alpaca.py", line 214, in initialize_strategy
    self.strategy = AdaptiveMultifactorStrategy(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adaptive_multifactor_strategy.py", line 183, in __init__
    self._load_data()
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adaptive_multifactor_strategy.py", line 266, in _load_data
    data = all_data[0]
           ~~~~~~~~^^^
IndexError: list index out of range
[2025-04-20 09:59:36] ERROR: Error al cargar datos: list index out of range
Traceback (most recent call last):
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adaptive_multifactor_strategy.py", line 266, in _load_data
    data = all_data[0]
           ~~~~~~~~^^^
IndexError: list index out of range
[2025-04-20 09:59:36] ERROR: Error al inicializar estrategia: list index out of range
Traceback (most recent call last):
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adapter_alpaca.py", line 214, in initialize_strategy
    self.strategy = AdaptiveMultifactorStrategy(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adaptive_multifactor_strategy.py", line 183, in __init__
    self._load_data()
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adaptive_multifactor_strategy.py", line 266, in _load_data
    data = all_data[0]
           ~~~~~~~~^^^
IndexError: list index out of range
[2025-04-20 09:59:36] ERROR: No se pudo inicializar la estrategia
[2025-04-20 10:00:12] ERROR: Error al cargar datos: list index out of range
Traceback (most recent call last):
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adaptive_multifactor_strategy.py", line 266, in _load_data
    data = all_data[0]
           ~~~~~~~~^^^
IndexError: list index out of range
[2025-04-20 10:00:12] ERROR: Error al inicializar estrategia: list index out of range
Traceback (most recent call last):
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adapter_alpaca.py", line 214, in initialize_strategy
    self.strategy = AdaptiveMultifactorStrategy(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adaptive_multifactor_strategy.py", line 183, in __init__
    self._load_data()
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adaptive_multifactor_strategy.py", line 266, in _load_data
    data = all_data[0]
           ~~~~~~~~^^^
IndexError: list index out of range
[2025-04-20 10:00:35] ERROR: Error al cargar datos: list index out of range
Traceback (most recent call last):
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adaptive_multifactor_strategy.py", line 266, in _load_data
    data = all_data[0]
           ~~~~~~~~^^^
IndexError: list index out of range
[2025-04-20 10:00:35] ERROR: Error al inicializar estrategia: list index out of range
Traceback (most recent call last):
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adapter_alpaca.py", line 214, in initialize_strategy
    self.strategy = AdaptiveMultifactorStrategy(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adaptive_multifactor_strategy.py", line 183, in __init__
    self._load_data()
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adaptive_multifactor_strategy.py", line 266, in _load_data
    data = all_data[0]
           ~~~~~~~~^^^
IndexError: list index out of range
[2025-04-20 10:00:41] ERROR: Error al cargar datos: list index out of range
Traceback (most recent call last):
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adaptive_multifactor_strategy.py", line 266, in _load_data
    data = all_data[0]
           ~~~~~~~~^^^
IndexError: list index out of range
[2025-04-20 10:00:41] ERROR: Error al inicializar estrategia: list index out of range
Traceback (most recent call last):
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adapter_alpaca.py", line 214, in initialize_strategy
    self.strategy = AdaptiveMultifactorStrategy(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adaptive_multifactor_strategy.py", line 183, in __init__
    self._load_data()
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adaptive_multifactor_strategy.py", line 266, in _load_data
    data = all_data[0]
           ~~~~~~~~^^^
IndexError: list index out of range
[2025-04-20 10:00:41] ERROR: No se pudo inicializar la estrategia
[2025-04-20 10:01:11] ERROR: Error al cargar datos: list index out of range
Traceback (most recent call last):
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adaptive_multifactor_strategy.py", line 266, in _load_data
    data = all_data[0]
           ~~~~~~~~^^^
IndexError: list index out of range
[2025-04-20 10:01:11] ERROR: Error al inicializar estrategia: list index out of range
Traceback (most recent call last):
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adapter_alpaca.py", line 214, in initialize_strategy
    self.strategy = AdaptiveMultifactorStrategy(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adaptive_multifactor_strategy.py", line 183, in __init__
    self._load_data()
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adaptive_multifactor_strategy.py", line 266, in _load_data
    data = all_data[0]
           ~~~~~~~~^^^
IndexError: list index out of range
[2025-04-20 10:01:16] ERROR: Error al cargar datos: list index out of range
Traceback (most recent call last):
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adaptive_multifactor_strategy.py", line 266, in _load_data
    data = all_data[0]
           ~~~~~~~~^^^
IndexError: list index out of range
[2025-04-20 10:01:16] ERROR: Error al inicializar estrategia: list index out of range
Traceback (most recent call last):
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adapter_alpaca.py", line 214, in initialize_strategy
    self.strategy = AdaptiveMultifactorStrategy(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adaptive_multifactor_strategy.py", line 183, in __init__
    self._load_data()
  File "/home/angel/Escritorio/startup/incubator/paper/multifactorial/adaptive_multifactor_strategy.py", line 266, in _load_data
    data = all_data[0]
           ~~~~~~~~^^^
IndexError: list index out of range
[2025-04-20 10:01:16] ERROR: No se pudo inicializar la estrategia
